export const BREEDS = [
  { id:1,  name:'Afghan',           group:'Hound',        api:'hound/afghan',
    stats:{Loyalty:72,Intelligence:65,Energy:75,Fluffiness:90,Trainability:45,Friendliness:60},
    fact:'One of the oldest dog breeds on earth — Afghans were bred in the mountains of Afghanistan and have been clocked near 40 mph.' },
  { id:2,  name:'African Wild Dog', group:'Wild',         api:null,
    stats:{Loyalty:85,Intelligence:75,Energy:95,Fluffiness:20,Trainability:30,Friendliness:40},
    fact:'Not domesticated. The African Wild Dog is a wild canid from sub-Saharan Africa — no two individuals share the same coat pattern.' },
  { id:3,  name:'Airedale',         group:'Terrier',      api:'airedale',
    stats:{Loyalty:82,Intelligence:80,Energy:85,Fluffiness:60,Trainability:75,Friendliness:78},
    fact:'The "King of Terriers" and the largest of all terrier breeds. Airedales served as messenger dogs during World War I.' },
  { id:4,  name:'American Hairless',group:'Terrier',      api:'terrier/american',
    stats:{Loyalty:88,Intelligence:75,Energy:70,Fluffiness:5,Trainability:82,Friendliness:90},
    fact:'One of the only hairless breeds native to the US and genuinely hypoallergenic.' },
  { id:5,  name:'American Spaniel', group:'Sporting',     api:'spaniel/cocker',
    stats:{Loyalty:88,Intelligence:78,Energy:80,Fluffiness:65,Trainability:82,Friendliness:90},
    fact:'Bred to flush birds from dense cover, the American Spaniel brings boundless energy to everything it does.' },
  { id:6,  name:'Basenji',          group:'Hound',        api:'basenji',
    stats:{Loyalty:70,Intelligence:72,Energy:85,Fluffiness:30,Trainability:40,Friendliness:65},
    fact:'The "barkless dog" from Central Africa. Basenjis cannot bark — instead they produce a unique sound called a baroo.' },
  { id:7,  name:'Basset',           group:'Hound',        api:'basset',
    stats:{Loyalty:82,Intelligence:65,Energy:45,Fluffiness:40,Trainability:55,Friendliness:85},
    fact:'Those long velvety ears sweep scents upward toward one of the most powerful noses in the canine world.' },
  { id:8,  name:'Beagle',           group:'Hound',        api:'beagle',
    stats:{Loyalty:85,Intelligence:70,Energy:80,Fluffiness:40,Trainability:68,Friendliness:90},
    fact:'Beagles are deployed at airports worldwide to sniff out illegal food. Their noses have around 220 million scent receptors.' },
  { id:9,  name:'Bearded Collie',   group:'Herding',      api:'collie/bearded',
    stats:{Loyalty:88,Intelligence:80,Energy:85,Fluffiness:85,Trainability:82,Friendliness:88},
    fact:'Called "Beardies," these shaggy herding dogs were bred to work the Scottish Highlands through any weather.' },
  { id:10, name:'Bermaise',         group:'Working',      api:'mountain/bernese',
    stats:{Loyalty:90,Intelligence:80,Energy:65,Fluffiness:92,Trainability:78,Friendliness:92},
    fact:'Bernese Mountain Dogs were Swiss farm dogs who pulled carts and drove cattle across the steep Alpine slopes.' },
  { id:11, name:'Bichon Frise',     group:'Non-Sporting', api:'frise/bichon',
    stats:{Loyalty:88,Intelligence:72,Energy:65,Fluffiness:95,Trainability:78,Friendliness:92},
    fact:'Their name means "curly lap dog" in French. The Bichon was a favourite of French royalty for centuries.' },
  { id:12, name:'Blenheim',         group:'Toy',          api:'spaniel/blenheim',
    stats:{Loyalty:90,Intelligence:75,Energy:60,Fluffiness:80,Trainability:80,Friendliness:95},
    fact:'A chestnut-and-white Cavalier King Charles Spaniel colour, named after Blenheim Palace where the breed was developed.' },
  { id:13, name:'Bloodhound',       group:'Hound',        api:'hound/blood',
    stats:{Loyalty:78,Intelligence:65,Energy:60,Fluffiness:45,Trainability:50,Friendliness:80},
    fact:"A Bloodhound's tracking is so accurate it's legally admissible in court. They can follow a trail over 130 miles long." },
  { id:14, name:'Bluetick',         group:'Hound',        api:'bluetick',
    stats:{Loyalty:82,Intelligence:68,Energy:80,Fluffiness:40,Trainability:60,Friendliness:78},
    fact:"A Southern coonhound with a distinctive blue-ticked coat — every dog's pattern is completely unique." },
  { id:15, name:'Border Collie',    group:'Herding',      api:'collie/border',
    stats:{Loyalty:90,Intelligence:100,Energy:95,Fluffiness:65,Trainability:98,Friendliness:80},
    fact:'Widely regarded as the most intelligent dog breed. Border Collies can learn a new command in under 5 repetitions.' },
  { id:16, name:'Borzoi',           group:'Hound',        api:'borzoi',
    stats:{Loyalty:72,Intelligence:68,Energy:80,Fluffiness:85,Trainability:55,Friendliness:62},
    fact:"Russian aristocratic sighthounds once used in wolf hunts by the Tsar's court. They can reach 37 mph." },
  { id:17, name:'Boston Terrier',   group:'Non-Sporting', api:'bulldog/boston',
    stats:{Loyalty:88,Intelligence:78,Energy:72,Fluffiness:15,Trainability:80,Friendliness:92},
    fact:'The first dog breed developed in the United States — recognized by the AKC in 1893.' },
  { id:18, name:'Boxer',            group:'Working',      api:'boxer',
    stats:{Loyalty:92,Intelligence:78,Energy:85,Fluffiness:15,Trainability:78,Friendliness:88},
    fact:'Boxers got their name from their habit of standing on hind legs and "boxing" with their front paws during play.' },
  { id:19, name:'Bull Mastiff',     group:'Working',      api:'mastiff/bull',
    stats:{Loyalty:92,Intelligence:75,Energy:55,Fluffiness:25,Trainability:70,Friendliness:75},
    fact:'Bred by English gamekeepers in the 1800s to catch poachers — 60% Mastiff, 40% Bulldog, 100% effective.' },
  { id:20, name:'Bull Terrier',     group:'Terrier',      api:'bullterrier/staffordshire',
    stats:{Loyalty:85,Intelligence:68,Energy:88,Fluffiness:15,Trainability:62,Friendliness:78},
    fact:'The only breed with a completely egg-shaped skull — a profile found nowhere else across 300+ recognized breeds.' },
  { id:21, name:'Bulldog',          group:'Non-Sporting', api:'bulldog/english',
    stats:{Loyalty:85,Intelligence:65,Energy:35,Fluffiness:20,Trainability:62,Friendliness:90},
    fact:'Despite the fierce look, Bulldogs are among the gentlest and most patient breeds ever developed.' },
  { id:22, name:'Cairn',            group:'Terrier',      api:'cairn',
    stats:{Loyalty:80,Intelligence:72,Energy:80,Fluffiness:55,Trainability:65,Friendliness:82},
    fact:'Toto from The Wizard of Oz was a Cairn Terrier! Originally bred to hunt rodents in Scottish cairns and stone walls.' },
  { id:23, name:'Chihuahua',        group:'Toy',          api:'chihuahua',
    stats:{Loyalty:90,Intelligence:72,Energy:70,Fluffiness:30,Trainability:62,Friendliness:65},
    fact:"The world's smallest dog breed — but present in Mexico since at least the 9th century." },
  { id:24, name:'Chinese Crested',  group:'Toy',          api:null,
    stats:{Loyalty:88,Intelligence:70,Energy:65,Fluffiness:25,Trainability:72,Friendliness:85},
    fact:'Comes in Hairless and Powderpuff varieties. The Hairless version has skin that feels surprisingly warm.' },
  { id:25, name:'Chow',             group:'Non-Sporting', api:'chow',
    stats:{Loyalty:75,Intelligence:72,Energy:55,Fluffiness:85,Trainability:58,Friendliness:55},
    fact:'Chow Chows have a blue-black tongue — a trait shared with only one other breed out of hundreds worldwide.' },
  { id:26, name:'Clumber',          group:'Sporting',     api:'clumber',
    stats:{Loyalty:85,Intelligence:72,Energy:50,Fluffiness:65,Trainability:72,Friendliness:85},
    fact:'The heaviest spaniel breed, originally developed for French and English nobility. Calm and quietly dignified.' },
  { id:27, name:'Cockapoo',         group:'Hybrid',       api:'cockapoo',
    stats:{Loyalty:92,Intelligence:82,Energy:75,Fluffiness:80,Trainability:88,Friendliness:95},
    fact:'One of the earliest "designer dogs" — a Cocker Spaniel + Poodle cross developed in the 1960s for low shedding.' },
  { id:28, name:'Cocker',           group:'Sporting',     api:'spaniel/cocker',
    stats:{Loyalty:90,Intelligence:78,Energy:75,Fluffiness:70,Trainability:82,Friendliness:90},
    fact:'The American Cocker Spaniel was the most popular breed in the US for the entire decade of the 1940s.' },
  { id:29, name:'Collie',           group:'Herding',      api:'collie/border',
    stats:{Loyalty:90,Intelligence:88,Energy:75,Fluffiness:80,Trainability:90,Friendliness:90},
    fact:'Lassie made this breed a global icon. Collies have been documented navigating hundreds of miles to return home.' },
  { id:30, name:'Corgi',            group:'Herding',      api:'corgi/pembroke',
    stats:{Loyalty:88,Intelligence:85,Energy:78,Fluffiness:70,Trainability:88,Friendliness:90},
    fact:"Queen Elizabeth II owned more than 30 Corgis in her lifetime. Welsh legend says they were mounts of fairy warriors." },
  { id:31, name:'Dalmation',        group:'Non-Sporting', api:'dalmatian',
    stats:{Loyalty:82,Intelligence:72,Energy:88,Fluffiness:15,Trainability:72,Friendliness:85},
    fact:'Dalmatians are born completely white — their famous spots appear and develop over the first few weeks of life.' },
  { id:32, name:'Dhole',            group:'Wild',         api:'dhole',
    stats:{Loyalty:75,Intelligence:70,Energy:95,Fluffiness:35,Trainability:20,Friendliness:30},
    fact:'A wild canid from Asia that hunts in packs using a distinctive whistle. Not a domestic dog.' },
  { id:33, name:'Dingo',            group:'Wild',         api:'dingo',
    stats:{Loyalty:60,Intelligence:68,Energy:90,Fluffiness:30,Trainability:20,Friendliness:35},
    fact:"Australia's semi-wild dog has lived on the continent for around 3,500 years." },
  { id:34, name:'Doberman',         group:'Working',      api:'doberman',
    stats:{Loyalty:95,Intelligence:88,Energy:85,Fluffiness:10,Trainability:92,Friendliness:75},
    fact:'Created by Karl Dobermann, a German tax collector who needed a formidable companion for dangerous rounds.' },
  { id:35, name:'Elk Hound',        group:'Hound',        api:'elkhound/norwegian',
    stats:{Loyalty:82,Intelligence:72,Energy:80,Fluffiness:70,Trainability:72,Friendliness:80},
    fact:'One of the most ancient Scandinavian breeds, found in Viking burial mounds thousands of years old.' },
  { id:36, name:'French Bulldog',   group:'Non-Sporting', api:'bulldog/french',
    stats:{Loyalty:88,Intelligence:72,Energy:55,Fluffiness:15,Trainability:78,Friendliness:92},
    fact:"As of 2023, the French Bulldog is the #1 most popular dog in the US — ending Labrador's 31-year reign." },
  { id:37, name:'German Sheperd',   group:'Herding',      api:'germanshepherd',
    stats:{Loyalty:95,Intelligence:92,Energy:82,Fluffiness:55,Trainability:96,Friendliness:78},
    fact:'The most versatile working breed in history — police K-9, military asset, guide dog, search and rescue.' },
  { id:38, name:'Golden Retriever', group:'Sporting',     api:'retriever/golden',
    stats:{Loyalty:95,Intelligence:88,Energy:80,Fluffiness:80,Trainability:92,Friendliness:99},
    fact:'Developed in the Scottish Highlands in the 1860s to retrieve waterfowl. Consistently a top-3 breed worldwide.' },
  { id:39, name:'Great Dane',       group:'Working',      api:'dane/great',
    stats:{Loyalty:85,Intelligence:72,Energy:60,Fluffiness:15,Trainability:72,Friendliness:88},
    fact:'Zeus, a Great Dane from Michigan, was certified as the world\'s tallest dog at 44 inches at the shoulder.' },
  { id:40, name:'Great Perenees',   group:'Working',      api:'pyrenees/great',
    stats:{Loyalty:85,Intelligence:72,Energy:60,Fluffiness:98,Trainability:68,Friendliness:82},
    fact:'Bred for freezing mountain conditions. Great Pyrenees have double dewclaws on hind feet for grip on snow.' },
  { id:41, name:'Greyhound',        group:'Hound',        api:'greyhound',
    stats:{Loyalty:80,Intelligence:70,Energy:90,Fluffiness:15,Trainability:68,Friendliness:78},
    fact:'The fastest dog breed at 45 mph — yet famous for being "40 mph couch potatoes" at home.' },
  { id:42, name:'Groenendael',      group:'Herding',      api:'groenendael',
    stats:{Loyalty:88,Intelligence:85,Energy:82,Fluffiness:75,Trainability:88,Friendliness:78},
    fact:'The all-black Belgian Shepherd, named after a village near Brussels. Elite herding and protection dogs.' },
  { id:43, name:'Irish Spaniel',    group:'Sporting',     api:'spaniel/irish',
    stats:{Loyalty:88,Intelligence:78,Energy:85,Fluffiness:60,Trainability:78,Friendliness:92},
    fact:'Nicknamed the "Clown of the Spaniel Family" for their reliably goofy personality. Natural-born swimmers.' },
  { id:44, name:'Irish Wolfhound',  group:'Hound',        api:'wolfhound/irish',
    stats:{Loyalty:85,Intelligence:70,Energy:65,Fluffiness:60,Trainability:70,Friendliness:90},
    fact:'The tallest dog breed by standard height. Despite their size, they are exceptionally gentle.' },
  { id:45, name:'Japanese Spaniel', group:'Toy',          api:'spaniel/japanese',
    stats:{Loyalty:88,Intelligence:72,Energy:55,Fluffiness:70,Trainability:78,Friendliness:88},
    fact:'The Japanese Chin was an imperial court companion — ownership was restricted to royalty for centuries.' },
  { id:46, name:'Komondor',         group:'Working',      api:'komondor',
    stats:{Loyalty:88,Intelligence:70,Energy:65,Fluffiness:100,Trainability:65,Friendliness:70},
    fact:"The Komondor's corded coat can develop over 1,900 individual cords and takes two full years to form." },
  { id:47, name:'Labradoodle',      group:'Hybrid',       api:'labradoodle',
    stats:{Loyalty:92,Intelligence:85,Energy:82,Fluffiness:80,Trainability:92,Friendliness:98},
    fact:'First bred in 1989 in Australia as a hypoallergenic guide dog for a blind woman whose husband had allergies.' },
  { id:48, name:'Labrador',         group:'Sporting',     api:'labrador',
    stats:{Loyalty:95,Intelligence:85,Energy:85,Fluffiness:45,Trainability:95,Friendliness:99},
    fact:'The Labrador Retriever held the #1 most popular breed spot in the US for 31 consecutive years — 1991 to 2022.' },
  { id:49, name:'Lhasa',            group:'Non-Sporting', api:'lhasa',
    stats:{Loyalty:80,Intelligence:70,Energy:55,Fluffiness:88,Trainability:65,Friendliness:72},
    fact:"Sacred temple dogs of Tibet, believed to bring good fortune. The Lhasa Apso was never sold — only given as a gift." },
  { id:50, name:'Malinois',         group:'Herding',      api:'malinois',
    stats:{Loyalty:92,Intelligence:92,Energy:98,Fluffiness:35,Trainability:96,Friendliness:70},
    fact:'The breed of choice for US Navy SEALs and the Secret Service. Cairo, on the 2011 Bin Laden raid, was a Malinois.' },
  { id:51, name:'Maltese',          group:'Toy',          api:'maltese',
    stats:{Loyalty:88,Intelligence:72,Energy:55,Fluffiness:92,Trainability:75,Friendliness:88},
    fact:'One of the oldest toy breeds — Ancient Greeks built tombs for their Maltese dogs over 2,000 years ago.' },
  { id:52, name:'Mex Hairless',     group:'Non-Sporting', api:'mexicanhairless',
    stats:{Loyalty:82,Intelligence:75,Energy:65,Fluffiness:5,Trainability:72,Friendliness:78},
    fact:'The Xoloitzcuintli (show-low-eetz-QUEENT-lee) is among the rarest breeds and was sacred to the Aztecs.' },
  { id:53, name:'Newfoundland',     group:'Working',      api:'newfoundland',
    stats:{Loyalty:90,Intelligence:78,Energy:60,Fluffiness:95,Trainability:82,Friendliness:95},
    fact:'Newfoundlands have webbed feet and a water-resistant coat. Documented life rescues by this breed number in the hundreds.' },
  { id:54, name:'Pekinese',         group:'Toy',          api:'pekinese',
    stats:{Loyalty:75,Intelligence:68,Energy:40,Fluffiness:88,Trainability:58,Friendliness:70},
    fact:'Bred exclusively for Chinese emperors. Under Tang Dynasty law, stealing one was punishable by death.' },
  { id:55, name:'Pit Bull',         group:'Terrier',      api:'pitbull',
    stats:{Loyalty:96,Intelligence:78,Energy:88,Fluffiness:20,Trainability:82,Friendliness:90},
    fact:'When properly raised, Pit Bulls are among the most loyal and human-devoted breeds — historically called "nanny dogs."' },
  { id:56, name:'Pomeranian',       group:'Toy',          api:'pomeranian',
    stats:{Loyalty:85,Intelligence:72,Energy:75,Fluffiness:95,Trainability:72,Friendliness:80},
    fact:"Queen Victoria's tiny Pomeranian sparked a European fashion for miniature Poms, dramatically shrinking the breed's size." },
  { id:57, name:'Poodle',           group:'Non-Sporting', api:'poodle',
    stats:{Loyalty:88,Intelligence:97,Energy:72,Fluffiness:90,Trainability:96,Friendliness:88},
    fact:'The classic show clip was functional — removing fur from joints during cold-water retrieves while keeping vital organs warm.' },
  { id:58, name:'Pug',              group:'Toy',          api:'pug',
    stats:{Loyalty:88,Intelligence:65,Energy:50,Fluffiness:20,Trainability:60,Friendliness:95},
    fact:'The Pug\'s motto: "multum in parvo" — a great deal in a small space. Imperial Chinese companions since the 10th century.' },
  { id:59, name:'Rhodesian',        group:'Hound',        api:'ridgeback/rhodesian',
    stats:{Loyalty:88,Intelligence:78,Energy:85,Fluffiness:25,Trainability:72,Friendliness:78},
    fact:'Bred to find lions and hold them at bay — not fight them — while waiting for the hunter to arrive.' },
  { id:60, name:'Rottweiler',       group:'Working',      api:'rottweiler',
    stats:{Loyalty:95,Intelligence:82,Energy:75,Fluffiness:20,Trainability:85,Friendliness:72},
    fact:'Descendant of ancient Roman drover dogs that traveled with the legions across Europe. One of the oldest lineages known.' },
  { id:61, name:'Saint Bernard',    group:'Working',      api:'stbernard',
    stats:{Loyalty:88,Intelligence:72,Energy:50,Fluffiness:88,Trainability:78,Friendliness:92},
    fact:'Barry der Menschenretter saved over 40 lives in the Swiss Alps in the early 1800s. A statue in Bern commemorates him.' },
  { id:62, name:'Schnauzer',        group:'Terrier',      api:'schnauzer',
    stats:{Loyalty:85,Intelligence:82,Energy:78,Fluffiness:55,Trainability:82,Friendliness:82},
    fact:'Those distinctive beard and eyebrows were originally protective — shielding the face when pursuing prey through brush.' },
  { id:63, name:'Scotch Terrier',   group:'Terrier',      api:'terrier/scottish',
    stats:{Loyalty:82,Intelligence:72,Energy:70,Fluffiness:60,Trainability:65,Friendliness:72},
    fact:'The most common presidential dog in US history — in the White House under FDR, Eisenhower, and George W. Bush.' },
  { id:64, name:'Shar_Pei',         group:'Non-Sporting', api:null,
    stats:{Loyalty:80,Intelligence:68,Energy:55,Fluffiness:60,Trainability:65,Friendliness:65},
    fact:'Those dramatic wrinkles were deliberate — excess loose skin made the dog significantly harder to grip in a fight.' },
  { id:65, name:'Shiba Inu',        group:'Non-Sporting', api:'shiba',
    stats:{Loyalty:75,Intelligence:78,Energy:72,Fluffiness:60,Trainability:62,Friendliness:68},
    fact:"Japan's most popular dog breed and the original internet meme dog — Kabosu the \"Doge\" is a Shiba Inu." },
  { id:66, name:'Shih-Tzu',         group:'Toy',          api:'shihtzu',
    stats:{Loyalty:85,Intelligence:68,Energy:50,Fluffiness:95,Trainability:68,Friendliness:88},
    fact:'The name means "lion dog" in Chinese. Bred to resemble Buddhist lions, kept exclusively by Chinese royalty for centuries.' },
  { id:67, name:'Siberian Husky',   group:'Working',      api:'husky',
    stats:{Loyalty:82,Intelligence:75,Energy:98,Fluffiness:88,Trainability:68,Friendliness:80},
    fact:"Huskies can run 100+ miles a day in freezing temps — a metabolic efficiency that physiologists still can't fully explain." },
  { id:68, name:'Vizsla',           group:'Sporting',     api:'vizsla',
    stats:{Loyalty:92,Intelligence:85,Energy:90,Fluffiness:25,Trainability:88,Friendliness:90},
    fact:'The only breed where coat and eye colour genetically match — both a distinctive golden rust. Natural-born pointers.' },
  { id:69, name:'Yorkie',           group:'Terrier',      api:'terrier/yorkshire',
    stats:{Loyalty:82,Intelligence:72,Energy:72,Fluffiness:88,Trainability:68,Friendliness:80},
    fact:'Yorkshire Terriers were bred as working ratters in 19th-century English textile mills. Today\'s lap dog is quite the evolution.' },
];

export const byName = Object.fromEntries(BREEDS.map(b => [b.name, b]));

export const STAT_COLORS = {
  Loyalty: '#ef4444',
  Intelligence: '#38bdf8',
  Energy: '#fbbf24',
  Fluffiness: '#a78bfa',
  Trainability: '#34d399',
  Friendliness: '#fb923c',
};

export const TYPE_COLORS = {
  Herding: '#065f46',
  Hound: '#92400e',
  Sporting: '#1e3a8a',
  Terrier: '#7f1d1d',
  Toy: '#831843',
  Working: '#4c1d95',
  'Non-Sporting': '#1e293b',
  Hybrid: '#164e63',
  Wild: '#422006',
};

export const GROUPS = ['All', 'Herding', 'Hound', 'Sporting', 'Terrier', 'Toy', 'Working', 'Non-Sporting', 'Hybrid', 'Wild'];
